version: "3.9"

services:
  web:
    container_name: team-up-web
    build: ./
    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 5
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:14.0-alpine
    restart: on-failure
    ports:
      - "5432:5432"
    env_file:
      - ./.env.prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    depends_on:
      - web

volumes:
  postgres_data_prod:
  static_volume:
  media_volume:
