version: "3.9"

services:
  web:
    container_name: team-up-web
    build: ./
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:14.0-alpine
    restart: on-failure
    ports:
      - "5432:5432"
    env_file:
      - ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: