# Generated by Django 4.0.1 on 2022-02-12 20:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_executoroffer_profileprojectstatus'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('vacant', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Вакантных мест')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Город')),
                ('online', models.BooleanField(blank=True, choices=[(None, 'Не указывать'), (False, 'Требуется присутствие'), (True, 'Присутствие не требуется')], default=None, null=True, verbose_name='Возможность работы онлайн')),
                ('verified', models.BooleanField(default=False, verbose_name='Подтвержден')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.profile', verbose_name='Владелец')),
                ('required_belbin', models.ManyToManyField(related_name='projects', to='tests.BelbinTest', verbose_name='Требуемые роли по Белбину')),
                ('required_specialization', models.ManyToManyField(related_name='projects', to='accounts.Specialization', verbose_name='Требуемые специализации')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='WorkerSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата')),
                ('work_hours', models.PositiveSmallIntegerField(default=40, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)], verbose_name='Часы работы в неделю')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_slots', to='accounts.profile', verbose_name='Профиль работника')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='projects.project', verbose_name='Проект')),
                ('role', models.ManyToManyField(related_name='worker_slots', to='tests.BelbinTest', verbose_name='Роли по Белбину')),
                ('specialization', models.ManyToManyField(related_name='worker_slots', to='accounts.Specialization', verbose_name='Специализации')),
            ],
            options={
                'verbose_name': 'Слот работника',
                'verbose_name_plural': 'Слоты работника',
            },
        ),
    ]
