# Generated by Django 4.0.1 on 2022-04-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, unique=True,
                                   verbose_name='Название'),
        ),
    ]
