# Generated by Django 4.0.1 on 2022-05-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['id'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
