# Generated by Django 4.0.1 on 2022-05-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
