# Generated by Django 4.0.1 on 2022-01-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BelbinTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30, verbose_name='Роль по Белбину')),
            ],
            options={
                'verbose_name': 'Роль по Белбину',
                'verbose_name_plural': 'Роли по Белбину',
            },
        ),
        migrations.CreateModel(
            name='LSQTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30, verbose_name='Роль по Хони-Мамфорду')),
            ],
            options={
                'verbose_name': 'Роль по Хони-Мамфорду',
                'verbose_name_plural': 'Роли по Хони-Мамфорду',
            },
        ),
        migrations.CreateModel(
            name='MBTITest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30, verbose_name='Роль по Майерсу-Бриггсу')),
            ],
            options={
                'verbose_name': 'Роль по Майерсу-Бриггсу',
                'verbose_name_plural': 'Роли по Майерсу-Бриггсу',
            },
        ),
    ]
