# Generated by Django 4.0.1 on 2022-01-29 18:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Отчество')),
                ('photo', models.ImageField(blank=True, default='profile_photos/empty.png', upload_to='profile_photos/', verbose_name='Фотография')),
                ('description', models.TextField(blank=True, default='Пользователь не рассказывает о себе', verbose_name='Описание')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc'])], verbose_name='Резюме')),
                ('remote', models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Не указывать'), (1, 'Онлайн'), (2, 'И онлайн, и оффлайн'), (3, 'Оффлайн')], null=True, verbose_name='Удаленная работа')),
                ('is_male', models.BooleanField(blank=True, choices=[(None, 'Не указывать'), (True, 'Мужской'), (False, 'Женский')], default=None, null=True, verbose_name='Пол')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Город')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(100)], verbose_name='Возраст')),
                ('verified', models.BooleanField(default=False, verbose_name='Подтвержден')),
                ('belbin', models.ManyToManyField(blank=True, related_name='profiles', to='tests.BelbinTest', verbose_name='Результат теста по Белбину')),
                ('lsq', models.ManyToManyField(blank=True, related_name='profiles', to='tests.LSQTest', verbose_name='Результат теста Хони-Мамфорда')),
                ('mbti', models.ManyToManyField(blank=True, related_name='profiles', to='tests.MBTITest', verbose_name='Результат теста Майерса-Бриггса')),
                ('specialization', models.ManyToManyField(blank=True, to='accounts.Specialization', verbose_name='Специализация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
