# Generated by Django 4.0.1 on 2022-02-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('value', models.CharField(max_length=20,
                                           verbose_name='Статус в проекте')),
            ],
            options={
                'verbose_name': 'Статус в проекте',
                'verbose_name_plural': 'Статусы в проекте',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
