# Generated by Django 4.0.1 on 2022-02-10 21:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_status_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль',
                     'verbose_name_plural': 'Профили'},
        ),
    ]
