# Generated by Django 4.0.1 on 2022-02-12 20:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutorOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата')),
                ('work_hours', models.PositiveSmallIntegerField(default=40, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)], verbose_name='Часы работы в неделю')),
            ],
            options={
                'verbose_name': 'Карточка работника',
                'verbose_name_plural': 'Карточки работника',
            },
        ),
        migrations.CreateModel(
            name='ProfileProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_statuses', to='accounts.profile', verbose_name='Профиль')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_statuses', to='accounts.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус вовлеченных в проект пользователей',
                'verbose_name_plural': 'Статусы вовлеченных в проект пользователей',
            },
        ),
    ]
