# Generated by Django 4.0.1 on 2022-02-12 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_executoroffer_profileprojectstatus'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileprojectstatus',
            name='worker_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_statuses', to='projects.workerslot', verbose_name='Слот работника'),
        ),
        migrations.AddField(
            model_name='executoroffer',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='executor_offer', to='accounts.profile'),
        ),
    ]
