# Generated by Django 4.0.1 on 2022-05-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executoroffer',
            options={'ordering': ['-id'], 'verbose_name': 'Карточка работника', 'verbose_name_plural': 'Карточки работника'},
        ),
    ]
