# Generated by Django 4.0.1 on 2022-05-14 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_executoroffer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ['name'], 'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
    ]
