# Generated by Django 4.0.1 on 2022-01-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
        migrations.AddField(
            model_name='profile',
            name='patronymic',
            field=models.CharField(blank=True, max_length=35,
                                   verbose_name='Отчество'),
        ),
    ]
