# Generated by Django 4.0.1 on 2022-01-19 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'main',
            '0007_project_alter_profile_city_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerslot',
            name='project',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='worker_slots',
                                    to='main.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='workerslot',
            name='specialization',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='worker_slots',
                                    to='main.specialization',
                                    verbose_name='Специализация'),
        ),
    ]
