# Generated by Django 4.0.1 on 2022-01-22 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0008_workerslot_project_alter_workerslot_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('value', models.CharField(max_length=20,
                                           verbose_name='Статус в проекте')),
            ],
            options={
                'verbose_name': 'Статус в проекте',
                'verbose_name_plural': 'Статусы в проекте',
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект',
                     'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='project',
            name='required_belbin',
            field=models.ManyToManyField(related_name='projects',
                                         to='main.BelbinTest',
                                         verbose_name='Требуемые роли по Белбину'),
        ),
        migrations.AddField(
            model_name='project',
            name='required_specialization',
            field=models.ManyToManyField(related_name='projects',
                                         to='main.Specialization',
                                         verbose_name='Требуемые специализации'),
        ),
        migrations.AlterField(
            model_name='workerslot',
            name='project',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='team', to='main.project',
                                    verbose_name='Проект'),
        ),
        migrations.RemoveField(
            model_name='workerslot',
            name='specialization',
        ),
        migrations.AddField(
            model_name='workerslot',
            name='specialization',
            field=models.ManyToManyField(related_name='worker_slots',
                                         to='main.Specialization',
                                         verbose_name='Специализации'),
        ),
        migrations.CreateModel(
            name='ProfileProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('profile', models.ForeignKey(null=True,
                                              on_delete=django.db.models.deletion.CASCADE,
                                              related_name='profile_statuses',
                                              to='main.profile',
                                              verbose_name='Профиль')),
                ('project', models.ForeignKey(null=True,
                                              on_delete=django.db.models.deletion.CASCADE,
                                              related_name='profile_statuses',
                                              to='main.project',
                                              verbose_name='Проект')),
                ('status', models.ForeignKey(null=True,
                                             on_delete=django.db.models.deletion.SET_NULL,
                                             related_name='profile_statuses',
                                             to='main.status',
                                             verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус вовлеченных в проект пользователей',
                'verbose_name_plural': 'Статусы вовлеченных в проект пользователей',
            },
        ),
    ]
