# Generated by Django 4.0.1 on 2022-01-22 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0010_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs',
                                   validators=[
                                       django.core.validators.FileExtensionValidator(
                                           ['pdf', 'docx'])],
                                   verbose_name='Резюме'),
        ),
    ]
