# Generated by Django 4.0.1 on 2022-01-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0018_alter_profile_patronymic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=30,
                                   null=True, verbose_name='Отчество'),
        ),
    ]
