# Generated by Django 4.0.1 on 2022-01-27 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_profile_cv_alter_project_offline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerslot',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_slots', to='main.profile', verbose_name='Профиль работника'),
        ),
    ]
