# Generated by Django 4.0.1 on 2022-01-29 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tests', '0001_initial'),
        ('main', '0021_alter_workerslot_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='belbin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lsq',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mbti',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='executoroffer',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='executor_offer', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='profileprojectstatus',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_statuses', to='accounts.profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='project',
            name='required_belbin',
            field=models.ManyToManyField(related_name='projects', to='tests.BelbinTest', verbose_name='Требуемые роли по Белбину'),
        ),
        migrations.AlterField(
            model_name='project',
            name='required_specialization',
            field=models.ManyToManyField(related_name='projects', to='accounts.Specialization', verbose_name='Требуемые специализации'),
        ),
        migrations.AlterField(
            model_name='workerslot',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_slots', to='accounts.profile', verbose_name='Профиль работника'),
        ),
        migrations.AlterField(
            model_name='workerslot',
            name='role',
            field=models.ManyToManyField(related_name='worker_slots', to='tests.BelbinTest', verbose_name='Роли по Белбину'),
        ),
        migrations.AlterField(
            model_name='workerslot',
            name='specialization',
            field=models.ManyToManyField(related_name='worker_slots', to='accounts.Specialization', verbose_name='Специализации'),
        ),
        migrations.DeleteModel(
            name='BelbinTest',
        ),
        migrations.DeleteModel(
            name='LSQTest',
        ),
        migrations.DeleteModel(
            name='MBTITest',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
