# Generated by Django 4.0.1 on 2022-01-31 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_profile_belbin_remove_profile_lsq_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='offline',
            new_name='online',
        ),
    ]
