# Generated by Django 4.0.1 on 2022-02-10 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_offline_project_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileprojectstatus',
            name='worker_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_statuses', to='main.workerslot', verbose_name='Слот работника'),
        ),
    ]
