# Generated by Django 4.0.1 on 2022-02-10 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
        ('main', '0025_remove_profileprojectstatus_project_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='projects',
                                    to='accounts.profile',
                                    verbose_name='Владелец'),
        ),
    ]
