# Generated by Django 4.0.1 on 2022-02-10 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileprojectstatus',
            name='worker_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_statuses', to='main.workerslot', verbose_name='Слот работника'),
        ),
    ]
