# Generated by Django 4.0.1 on 2022-02-10 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_status_alter_profile_options'),
        ('main', '0027_alter_profileprojectstatus_worker_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileprojectstatus',
            name='status',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='profile_statuses',
                                    to='accounts.status',
                                    verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
